function createfigure(X1, ymatrix1, X2, ymatrix2, X3, ymatrix3, X4, ymatrix4, X5, ymatrix5, X6, ymatrix6)
%CREATEFIGURE(X1, ymatrix1, X2, ymatrix2, X3, ymatrix3, X4, ymatrix4, X5, ymatrix5, X6, ymatrix6)
%  X1:  stairs x
%  YMATRIX1:  stairs matrix data
%  X2:  stairs x
%  YMATRIX2:  stairs matrix data
%  X3:  stairs x
%  YMATRIX3:  stairs matrix data
%  X4:  stairs x
%  YMATRIX4:  stairs matrix data
%  X5:  stairs x
%  YMATRIX5:  stairs matrix data
%  X6:  stairs x
%  YMATRIX6:  stairs matrix data

%  Auto-generated by MATLAB on 23-Nov-2021 19:23:52

% Create figure
figure1 = figure('Color',[1 1 1],'OuterPosition',[458 93 1308 944]);

% Create subplot
subplot1 = subplot(3,2,1);
hold(subplot1,'on');

% Create multiple lines using matrix input to stairs
stairs1 = stairs(X1,ymatrix1,'LineWidth',1);
set(stairs1(1),'DisplayName','Predicted Survival','Color',[1 0 0]);
set(stairs1(2),'DisplayName','Actual Survival','LineStyle','-.',...
    'Color',[0 0 1]);

% Create ylabel
ylabel('Survival Probability');

% Create title
title('Radiomics + Treatment Data (Best K-Fold)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0 26]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0 1.1]);
box(subplot1,'on');
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'TickDir','out','XTick',[0 2 4 6 8 10 12 14 16 18 20 22 24],...
    'XTickLabel',...
    {'    0\newline   21','    2\newline   20','    4\newline   17','    6\newline   16','    8\newline   15','   10\newline   12','   12\newline   12','   14\newline   11','   16\newline   10','   18\newline   10','   20\newline    8','   22\newline    8','   24\newline    8'},...
    'YTick',[0 0.2 0.4 0.6 0.8 1]);
% Create legend
legend(subplot1,'show');

% Create subplot
subplot2 = subplot(3,2,2);
hold(subplot2,'on');

% Create multiple lines using matrix input to stairs
stairs2 = stairs(X2,ymatrix2,'LineWidth',1);
set(stairs2(1),'DisplayName','Predicted Survival','Color',[1 0 0]);
set(stairs2(2),'DisplayName','Actual Survival','LineStyle','-.',...
    'Color',[0 0 1]);

% Create ylabel
ylabel('Survival Probability');

% Create title
title('Radiomics + Treatment Data (Worst K-Fold)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0 26]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0 1.1]);
box(subplot2,'on');
hold(subplot2,'off');
% Set the remaining axes properties
set(subplot2,'TickDir','out','XTick',[0 2 4 6 8 10 12 14 16 18 20 22 24],...
    'XTickLabel',...
    {'    0\newline   20','    2\newline   20','    4\newline   19','    6\newline   19','    8\newline   17','   10\newline   17','   12\newline   13','   14\newline   11','   16\newline    7','   18\newline    7','   20\newline    7','   22\newline    7','   24\newline    7'},...
    'YTick',[0 0.2 0.4 0.6 0.8 1]);
% Create legend
legend(subplot2,'show');

% Create subplot
subplot3 = subplot(3,2,3);
hold(subplot3,'on');

% Create multiple lines using matrix input to stairs
stairs3 = stairs(X3,ymatrix3,'LineWidth',1);
set(stairs3(1),'DisplayName','Predicted Survival','Color',[1 0 0]);
set(stairs3(2),'DisplayName','Actual Survival','LineStyle','-.',...
    'Color',[0 0 1]);

% Create ylabel
ylabel('Survival Probability');

% Create title
title('Radiomics Data Only (Best K-Fold)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[0 26]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[0 1.1]);
box(subplot3,'on');
hold(subplot3,'off');
% Set the remaining axes properties
set(subplot3,'TickDir','out','XTick',[0 2 4 6 8 10 12 14 16 18 20 22 24],...
    'XTickLabel',...
    {'    0\newline   21','    2\newline   20','    4\newline   18','    6\newline   17','    8\newline   16','   10\newline   14','   12\newline   14','   14\newline   12','   16\newline   11','   18\newline   11','   20\newline    9','   22\newline    9','   24\newline    9'},...
    'YTick',[0 0.2 0.4 0.6 0.8 1]);
% Create legend
legend(subplot3,'show');

% Create subplot
subplot4 = subplot(3,2,4);
hold(subplot4,'on');

% Create multiple lines using matrix input to stairs
stairs4 = stairs(X4,ymatrix4,'LineWidth',1);
set(stairs4(1),'DisplayName','Predicted Survival','Color',[1 0 0]);
set(stairs4(2),'DisplayName','Actual Survival','LineStyle','-.',...
    'Color',[0 0 1]);

% Create ylabel
ylabel('Survival Probability');

% Create title
title('Radiomics Data Only (Worst K-Fold)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot4,[0 26]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot4,[0 1.1]);
box(subplot4,'on');
hold(subplot4,'off');
% Set the remaining axes properties
set(subplot4,'TickDir','out','XTick',[0 2 4 6 8 10 12 14 16 18 20 22 24],...
    'XTickLabel',...
    {'    0\newline   21','    2\newline   18','    4\newline   16','    6\newline   13','    8\newline   11','   10\newline   11','   12\newline   11','   14\newline    9','   16\newline    9','   18\newline    7','   20\newline    7','   22\newline    7','   24\newline    7'},...
    'YTick',[0 0.2 0.4 0.6 0.8 1]);
% Create legend
legend(subplot4,'show');

% Create subplot
subplot5 = subplot(3,2,5);
hold(subplot5,'on');

% Create multiple lines using matrix input to stairs
stairs5 = stairs(X5,ymatrix5,'LineWidth',1);
set(stairs5(1),'DisplayName','Predicted Survival','Color',[1 0 0]);
set(stairs5(2),'DisplayName','Actual Survival','LineStyle','-.',...
    'Color',[0 0 1]);

% Create ylabel
ylabel('Survival Probability');

% Create title
title('Treatment Data Only (Best K-Fold)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot5,[0 26]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot5,[0 1.1]);
box(subplot5,'on');
hold(subplot5,'off');
% Set the remaining axes properties
set(subplot5,'TickDir','out','XTick',[0 2 4 6 8 10 12 14 16 18 20 22 24],...
    'XTickLabel',...
    {'    0\newline   21','    2\newline   20','    4\newline   17','    6\newline   16','    8\newline   15','   10\newline   13','   12\newline   13','   14\newline   13','   16\newline   11','   18\newline   11','   20\newline   10','   22\newline   10','   24\newline   10'},...
    'YTick',[0 0.2 0.4 0.6 0.8 1]);
% Create legend
legend(subplot5,'show');

% Create subplot
subplot6 = subplot(3,2,6);
hold(subplot6,'on');

% Create multiple lines using matrix input to stairs
stairs6 = stairs(X6,ymatrix6,'LineWidth',1);
set(stairs6(1),'DisplayName','Predicted Survival','Color',[1 0 0]);
set(stairs6(2),'DisplayName','Actual Survival','LineStyle','-.',...
    'Color',[0 0 1]);

% Create ylabel
ylabel('Survival Probability');

% Create title
title('Treatment Data Only (Worst K-Fold)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot6,[0 26]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot6,[0 1.1]);
box(subplot6,'on');
hold(subplot6,'off');
% Set the remaining axes properties
set(subplot6,'TickDir','out','XTick',[0 2 4 6 8 10 12 14 16 18 20 22 24],...
    'XTickLabel',...
    {'    0\newline   21','    2\newline   21','    4\newline   19','    6\newline   19','    8\newline   16','   10\newline   16','   12\newline   11','   14\newline   10','   16\newline    6','   18\newline    6','   20\newline    6','   22\newline    6','   24\newline    6'},...
    'YTick',[0 0.2 0.4 0.6 0.8 1]);
% Create legend
legend(subplot6,'show');

% Create sgtitle
sgtitle(figure1,...
    'Predicted and Actual Survival (Freedom From Local Progression)');

% Create textbox
annotation(figure1,'textbox',...
    [0.0907832817337463 0.377203290246768 0.0237678018575852 0.0152761457109283],...
    'String',{'Month'},...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.0915572755417959 0.0857814336075199 0.0237678018575852 0.0152761457109283],...
    'String',{'Month'},...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.532733746130032 0.376028202115158 0.0237678018575853 0.0152761457109283],...
    'String',{'Month'},...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.488616099071208 0.36545240893067 0.083365325077399 0.00470035252643963],...
    'String','Number At Risk',...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.533507739938081 0.0846063454759101 0.0237678018575853 0.0152761457109283],...
    'String',{'Month'},...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.489390092879258 0.0740305522914214 0.0841393188854479 0.00470035252643969],...
    'String','Number At Risk',...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.048213622291022 0.0681551116333725 0.0841393188854486 0.0105757931844886],...
    'String','Number At Risk',...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.0466656346749229 0.370152761457109 0.083365325077399 6.10622663543836e-16],...
    'String','Number At Risk',...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.0907832817337462 0.668625146886016 0.0237678018575852 0.0152761457109283],...
    'String',{'Month'},...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.0466656346749228 0.656874265569918 0.0864613003095973 0.00470035252643963],...
    'String','Number At Risk',...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1],...
    'BackgroundColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.531959752321982 0.667450058754406 0.0237678018575852 0.0152761457109283],...
    'String',{'Month'},...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.487842105263159 0.649823736780258 0.0841393188854482 0.0117508813160986],...
    'String','Number At Risk',...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

